### ISSUE TITLE
[ACTION] Pipedrive: add new contacts, deals, activities. Move deal to new stage.

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#37]

**Comment by adamd** [comment]
Action-wise, it would be useful to add new contacts, deals, and activities. Plus, moving deals to new stages.

**Comment by dylburger** [comment]
Pipedrive has been integrated. Leaving this ticket open and renaming it to capture the actions use cases.

**Comment by sergioeliot2039** [comment]
Hey there, I have implemented almost all actions there, just instead of Move deal to a new stage, update deal was implemented: the stage is a property of a deal, so that can be used for moving the deal to the next stage in a Pipedrive's pipeline. Links below:

Add new contact.
Contacts can be either a person or an organization:
add new person workflow: https://pipedream.com/@sergio/pipedrive-add-person-p_PACZaG/edit
action: https://pipedream.com/actions/a_K5iL2M/edit
add new organization workflow: https://pipedream.com/@sergio/pipedrive-add-organization-p_ZJClBZ/edit
action:  https://pipedream.com/actions/a_WYiEeg/edit

add new deal:
workflow> https://pipedream.com/@sergio/pipedrive-add-new-deal-p_dDCawm/edit
action: https://pipedream.com/actions/a_EViLor/edit

add new activity:
workflow > https://pipedream.com/@sergio/pipedrive-add-activity-p_6lCj8A/edit
action > https://pipedream.com/actions/a_k6iKYA/edit

update deal:
workflow > https://pipedream.com/@sergio/pipedrive-update-deal-p_brC7z1/edit
action > https://pipedream.com/actions/a_vgi48J/edit

And that's it. All should be good, if something is noticed don't hesitate to let me know. Thanks!
Sergio
